name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew update
        brew install tcl-tk autoconf
        find /opt -name tclConfig.sh
    - name: configure
      run: |
        autoreconf -vi
        PREFIX=/opt/homebrew
        ./configure --with-tcl=$PREFIX/lib --prefix=$PREFIX
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: test
      run: make test
